
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='afaqLuxV3:';
const get=(k,f=null)=>{try{const v=localStorage.getItem(KEY+k);return v?JSON.parse(v):f}catch{return f}};
const set=(k,v)=>{try{localStorage.setItem(KEY+k,JSON.stringify(v))}catch{}};
const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const dateAr=()=>new Date().toLocaleDateString('ar-AE',{weekday:'long',year:'numeric',month:'long',day:'numeric'});
const dayKey=i=>{const d=new Date();d.setDate(d.getDate()-i);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const dayLabel=i=>{const d=new Date();d.setDate(d.getDate()-i);return d.toLocaleDateString('ar-AE',{weekday:'short'})};
const icons={home:'M4 11.5 12 5l8 6.5V20H4z',daily:'M12 3l2.4 5 5.6.8-4 4 1 5.6-5-2.7-5 2.7 1-5.6-4-4 5.6-.8z',tools:'M5 5h14v4H5zM5 15h14v4H5zM8 9v6M16 9v6',dashboard:'M5 19V9M12 19V5M19 19v-8',settings:'M12 15.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7zM4 12h2M18 12h2M12 4v2M12 18v2',search:'M11 18a7 7 0 110-14 7 7 0 010 14zM20 20l-3.2-3.2',back:'M15 6l-6 6 6 6',habit:'M5 12l4 4L19 6',focus:'M12 7v5l3 2M12 22a10 10 0 100-20 10 10 0 000 20z',mood:'M12 21s-7-4.3-7-10a4.5 4.5 0 018-2.8A4.5 4.5 0 0121 11c0 5.7-9 10-9 10z',breath:'M12 4c4 4 4 12 0 16-4-4-4-12 0-16zM4 12c4-4 12-4 16 0-4 4-12 4-16 0z',journal:'M7 4h10v16H7zM9 8h6M9 12h6M9 16h4',goal:'M12 20a8 8 0 100-16 8 8 0 000 16zM12 16a4 4 0 100-8 4 4 0 000 8zM12 12h.01',water:'M12 3s6 6.2 6 11a6 6 0 11-12 0c0-4.8 6-11 6-11z',energy:'M13 2L4 14h7l-1 8 9-12h-7z',matrix:'M4 4h7v7H4zM13 4h7v7h-7zM4 13h7v7H4zM13 13h7v7h-7z',wheel:'M12 21a9 9 0 100-18 9 9 0 000 18zM12 3v18M3 12h18',gratitude:'M12 20s-7-4-7-10a4 4 0 017-2 4 4 0 017 2c0 6-7 10-7 10z',routine:'M7 4h10M7 12h10M7 20h10M4 4h.01M4 12h.01M4 20h.01',award:'M12 15a6 6 0 100-12 6 6 0 000 12zM9 14l-1 7 4-2 4 2-1-7'};
function svg(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="${icons[name]||icons.tools}"/></svg>`}
const tips=['ابدأ بخطوة صغيرة يمكن تنفيذها حتى في يوم مزدحم.','اجعل العادة مرتبطة بشيء موجود أصلًا: بعد القهوة أو بعد الصلاة أو بعد إغلاق اللابتوب.','الاستمرار أهم من المثالية؛ لا تنتظر يومًا مثاليًا لتبدأ.','اكتب أولوية واحدة قبل فتح الهاتف.','خفف مقاومة البداية: دقيقتان تكفيان لفتح المسار.','راجع يومك بسؤال: ما الشيء الذي يستحق تكراره غدًا؟','اجعل البيئة تخدمك: ضع الشيء المفيد في مكان ظاهر.','اختر عادة واحدة لهذا الأسبوع بدل تغيير كل شيء دفعة واحدة.'];
const tools=[['daily','نصيحة اليوم','إلهام عملي يومي','daily'],['mood','مؤشر المزاج','تاريخ وملاحظة يومية','mood'],['habits','لوحة العادات','تتبّع أسبوعي وستريك','habit'],['focus','مؤقت التركيز','جلسات ومحفوظات','focus'],['breath','تنفس هادئ','تمرين 60 ثانية','breath'],['reflection','سؤال للتأمل','أسئلة عميقة وحفظ محلي','journal'],['gratitude','دفتر الامتنان','امتنان وستريك','gratitude'],['wheel','عجلة الحياة','توازن بصري وخطة','wheel'],['goals','مخطط الأهداف','هدف، سبب، خطوات','goal'],['matrix','مصفوفة الأولويات','عاجل/مهم','matrix'],['energy','تدقيق الطاقة','ما يزيدك وما يستهلكك','energy'],['routine','روتين يومي','صباحي ومسائي','routine'],['journal','المفكرة','ملاحظات منظمة','journal'],['weekly','مراجعة أسبوعية','تعلم وخطة الأسبوع','dashboard'],['achievements','الإنجازات','شارات تحفيزية','award']];
const habits=['شرب ماء','قراءة 5 دقائق','تنفس دقيقة','ترتيب المكتب','مشي قصير','كتابة فكرة','تقليل الهاتف','مراجعة هدف'];
const moods=[['هادئ','حافظ على هذا الهدوء واختر خطوة واحدة فقط.'],['مشغول','اختر أولوية واحدة وضع الباقي في وقت لاحق.'],['متردد','اكتب الخيارين واختر الخطوة الأقل مقاومة.'],['مرهق','خفف المتطلبات اليوم واجعل الهدف صغيرًا.'],['متحمس','حوّل الحماس إلى عادة صغيرة قابلة للتكرار.']];
const wheelAreas=['الصحة','العلاقات','العمل','المال','النمو','الهدوء','البيئة','الترفيه'];
const questions=['ما الشيء الذي أريد تبسيطه اليوم؟','ما الخطوة الصغيرة الممكنة الآن؟','ما الشيء الذي يمنحني طاقة ويستحق وقتًا أكثر؟','ما عادة واحدة لو ثبتت ستغيّر أسبوعي؟','ما الشيء الذي أستطيع تركه دون خسارة؟','ما القرار الذي يحتاج وضوحًا لا استعجالًا؟'];
let stack=['home'], currentTip=tips[new Date().getDate()%tips.length], timer=null,total=25*60,remain=25*60,breathTimer=null;
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function route(id,push=true){if(push)stack.push(id);$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.go===id));$('#backBtn').classList.toggle('hidden',['home','daily','tools','dashboard','settings'].includes(id));$('#topTitle').textContent=({home:'آفاق',daily:'يومك',tools:'الأدوات',dashboard:'التقدم',settings:'الإعدادات'})[id]||tools.find(t=>t[0]===id)?.[1]||'آفاق';window.scrollTo(0,0);render(id)}
function back(){if(stack.length>1){stack.pop();route(stack[stack.length-1],false)}}
function init(){document.documentElement.setAttribute('data-theme',get('theme','light'));$('#themeBtn').innerHTML=svg('settings');$('#searchBtn').innerHTML=svg('search');$('#backBtn').innerHTML=svg('back');$$('.nav-btn').forEach(b=>{b.querySelector('.nav-ico').innerHTML=svg(b.dataset.go==='daily'?'daily':b.dataset.go)});$$('[data-go]').forEach(b=>b.onclick=()=>route(b.dataset.go));$('#backBtn').onclick=back;$('#themeBtn').onclick=()=>{const next=document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',next);set('theme',next)};$('#searchBtn').onclick=showSearch;$('#closeSearch').onclick=()=>$('#searchOverlay').classList.remove('show');$('#searchInput').oninput=e=>renderSearch(e.target.value);route('home',false);if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
function stat(){const h=get('habits',{}),j=get('journal',[]),g=get('gratitude',[]),f=get('focusSessions',{}),w=get('wheel',null);let done=0;Object.values(h).forEach(v=>Object.values(v.days||{}).forEach(x=>done+=x?1:0));return{habitDone:done,journal:j.length,gratitude:g.length,focus:f[today()]||0,wheel:w?Math.round(w.avg):0,score:Math.min(100,done*3+j.length*5+g.length*5+(f[today()]||0)*8+(w?15:0))}}
function render(id){({home,daily,tools:toolsScreen,dashboard,settings,habits:habitScreen,focus,mood,breath,reflection,gratitude,wheel,goals,matrix,energy,routine,journal,weekly,achievements}[id]||home)()}
function home(){const s=stat();$('#home').innerHTML=`<div class="hero-card card"><div><div class="kicker">لوحة يومك</div><h1>اجعل اليوم أوضح</h1><p class="lead">متابعة يومية للتطور، الالتزام، العادات، التركيز، والتأمل الذاتي.</p><div class="hero-stat-grid"><div class="hero-stat"><b>${s.score}%</b><span>مؤشر التطور</span></div><div class="hero-stat"><b>${s.habitDone}</b><span>إنجاز عادة</span></div><div class="hero-stat"><b>${s.focus}</b><span>جلسات تركيز</span></div></div></div><button class="btn gold" data-go="daily">ابدأ فحص اليوم</button></div><div class="card"><div class="kicker">نصيحة اليوم</div><p class="lux-title">${currentTip}</p><div class="row" style="margin-top:14px"><button class="btn outline" data-go="daily">افتح خطة اليوم</button><button class="btn outline" onclick="newHomeTip()">نصيحة أخرى</button></div></div><div class="section-row"><h2>الأكثر استخدامًا</h2><span>دخول يومي سريع</span></div><div class="grid two">${['habits','focus','mood','journal'].map(id=>toolCard(id)).join('')}</div><div class="ad">مكان إعلان لاحقًا</div>`;bindGo()}
function toolCard(id){const t=tools.find(x=>x[0]===id);return `<button class="tool-card" data-go="${id}"><span class="tool-icon">${svg(t[3])}</span><strong>${t[1]}</strong><span>${t[2]}</span></button>`}
function newHomeTip(){currentTip=tips[Math.floor(Math.random()*tips.length)];home()}
function daily(){const s=stat();$('#daily').innerHTML=`<div class="kicker">فحص اليوم</div><h1>خطة يومية مختصرة</h1><p class="lead">ثلاث خطوات تجعل آفاق عادة يومية: تحقق، نفّذ، راجع.</p><div class="card"><h3>مؤشر التطور اليومي</h3><div class="big">${s.score}%</div><div class="meter"><span style="width:${s.score}%"></span></div></div><div class="grid"><button class="tool-card" data-go="mood"><span class="tool-icon">${svg('mood')}</span><strong>سجل حالتك</strong><span>خطوة وعي سريعة</span></button><button class="tool-card" data-go="habits"><span class="tool-icon">${svg('habit')}</span><strong>أنجز عادة اليوم</strong><span>حافظ على الاستمرارية</span></button><button class="tool-card" data-go="reflection"><span class="tool-icon">${svg('journal')}</span><strong>اكتب تأملًا قصيرًا</strong><span>دقيقة مراجعة ذاتية</span></button><button class="tool-card" data-go="weekly"><span class="tool-icon">${svg('dashboard')}</span><strong>راجع الأسبوع</strong><span>استخرج درسًا وخطة</span></button></div>`;bindGo()}
function toolsScreen(){ $('#tools').innerHTML=`<div class="kicker">مكتبة الأدوات</div><h1>كل أدوات آفاق</h1><p class="lead">أدوات مستوحاة من مفاهيم بناء العادات، الأولويات، الامتنان، والتوازن الحياتي.</p><div class="grid two">${tools.map(t=>toolCard(t[0])).join('')}</div>`;bindGo()}
function dashboard(){const s=stat();$('#dashboard').innerHTML=`<div class="kicker">لوحة التقدم</div><h1>تطورك في آفاق</h1><p class="lead">هنا ترى الالتزام بشكل بصري حتى تعرف أين تتحسن وأين تحتاج خطوة صغيرة.</p><div class="card"><h3>مؤشر التطور</h3><div class="big">${s.score}%</div><div class="meter"><span style="width:${s.score}%"></span></div></div><div class="grid two"><div class="card"><span class="panel-icon">${svg('habit')}</span><h3>${s.habitDone}</h3><p class="lead">إنجازات العادات</p></div><div class="card"><span class="panel-icon">${svg('journal')}</span><h3>${s.journal}</h3><p class="lead">ملاحظات محفوظة</p></div><div class="card"><span class="panel-icon">${svg('gratitude')}</span><h3>${s.gratitude}</h3><p class="lead">تدوينات امتنان</p></div><div class="card"><span class="panel-icon">${svg('focus')}</span><h3>${s.focus}</h3><p class="lead">جلسات تركيز اليوم</p></div></div>`}
function settings(){ $('#settings').innerHTML=`<div class="kicker">الإعدادات</div><h1>إعدادات آفاق</h1><div class="card"><h3>الثيم</h3><p class="lead">الوضع الحالي: ${document.documentElement.getAttribute('data-theme')==='dark'?'داكن':'فاتح'}</p><button class="btn" onclick="$('#themeBtn').click();settings()">تغيير الثيم</button></div><div class="card"><h3>التنويه القانوني</h3><p class="lead">تطبيق آفاق مخصص لتطوير نمط الحياة، التأمل الذاتي، وبناء العادات اليومية. لا يقدم التطبيق تشخيصًا طبيًا أو علاجًا نفسيًا، ولا يغني عن استشارة مختص عند الحاجة.</p></div><div class="card"><h3>الخصوصية</h3><p class="lead">لا يوجد تسجيل دخول. البيانات تُحفظ محليًا داخل جهاز المستخدم.</p><button class="btn danger" onclick="clearData()">مسح البيانات المحلية</button></div>`}
function clearData(){if(confirm('حذف كل البيانات المحلية؟')){Object.keys(localStorage).filter(k=>k.startsWith(KEY)).forEach(k=>localStorage.removeItem(k));toast('تم مسح البيانات');route('home')}}
function habitScreen(){const h=get('habits',{});habits.forEach(x=>{if(!h[x])h[x]={days:{}}});set('habits',h);$('#habits').innerHTML=`<div class="kicker">لوحة العادات</div><h1>استمرارية أسبوعية</h1><p class="lead">اضغط على اليوم الحالي لتسجيل العادة. صممناها على فكرة العادة الصغيرة والربط اليومي.</p><div class="grid">${habits.map(hh=>habitRow(hh,h[hh])).join('')}</div>`}
function habitRow(name,obj){return `<div class="card"><h3>${name}</h3><div class="calendar">${[6,5,4,3,2,1,0].map(i=>{const k=dayKey(i),done=obj.days[k];return `<button class="${done?'done':''}" onclick="toggleHabit('${name}','${k}')">${i===0?'اليوم':dayLabel(i)}</button>`}).join('')}</div></div>`}
function toggleHabit(n,k){const h=get('habits',{});h[n]=h[n]||{days:{}};h[n].days[k]=!h[n].days[k];set('habits',h);habitScreen();updateStatsAfterAction('تم تحديث العادة')}
function focus(){updateTimer();$('#focus').innerHTML=`<div class="kicker">مؤقت التركيز</div><h1>جلسة إنجاز</h1><p class="lead">اختر مهمة واحدة فقط. التركيز اليومي القصير يبني التزامًا ملموسًا.</p><div class="card"><textarea id="focusTask" placeholder="ما المهمة الوحيدة الآن؟"></textarea><div class="timer" id="timerView">${fmt(remain)}</div><div class="chip-list"><button class="chip ${total===1500?'active':''}" onclick="setFocus(25)">25 دقيقة</button><button class="chip ${total===900?'active':''}" onclick="setFocus(15)">15 دقيقة</button><button class="chip ${total===300?'active':''}" onclick="setFocus(5)">5 دقائق</button></div><div class="row"><button class="btn" onclick="toggleTimer()">${timer?'إيقاف مؤقت':'ابدأ'}</button><button class="btn outline" onclick="resetTimer()">إعادة</button></div></div>`}
function fmt(x){return String(Math.floor(x/60)).padStart(2,'0')+':'+String(x%60).padStart(2,'0')}function updateTimer(){const v=$('#timerView');if(v)v.textContent=fmt(remain)}function setFocus(m){if(timer)return;total=m*60;remain=total;focus()}function toggleTimer(){if(timer){clearInterval(timer);timer=null;focus();return}timer=setInterval(()=>{remain--;updateTimer();if(remain<=0){clearInterval(timer);timer=null;const f=get('focusSessions',{});f[today()]=(f[today()]||0)+1;set('focusSessions',f);toast('انتهت جلسة التركيز');remain=total;focus()}},1000);focus()}function resetTimer(){clearInterval(timer);timer=null;remain=total;focus()}
function mood(){const hist=get('mood',{});$('#mood').innerHTML=`<div class="kicker">مؤشر المزاج</div><h1>كيف يبدو يومك؟</h1><p class="lead">اختيار الحالة يحفظ تاريخًا يساعدك على ملاحظة الأنماط.</p><div class="grid">${moods.map((m,i)=>`<button class="tool-card" onclick="setMood('${m[0]}')"><span class="tool-icon">${svg('mood')}</span><strong>${m[0]}</strong><span>${m[1]}</span></button>`).join('')}</div><div class="card"><h3>آخر 7 أيام</h3><div class="mini-grid">${[6,5,4,3,2,1,0].map(i=>`<div class="day-dot ${hist[dayKey(i)]?'done':''}">${hist[dayKey(i)]||dayLabel(i)}</div>`).join('')}</div></div>`}
function setMood(m){const hist=get('mood',{});hist[today()]=m;set('mood',hist);toast('تم تسجيل الحالة');mood()}
function breath(){clearInterval(breathTimer);$('#breath').innerHTML=`<div class="kicker">تنفس</div><h1>دقيقة هدوء</h1><p class="lead">تمرين قصير لا يحتوي إعلانات مزعجة ويستخدم حركة بصرية هادئة.</p><div class="card breath-wrap"><div class="breath-circle" id="breathCircle">جاهز؟</div></div><div class="row"><button class="btn" onclick="startBreath()">ابدأ</button><button class="btn outline" onclick="stopBreath()">إيقاف</button></div>`}function startBreath(){const c=$('#breathCircle');c.classList.add('running');c.textContent='تنفّس';clearTimeout(breathTimer);breathTimer=setTimeout(()=>{stopBreath();toast('أحسنت، انتهى التمرين')},60000)}function stopBreath(){const c=$('#breathCircle');if(c){c.classList.remove('running');c.textContent='جاهز؟'}clearTimeout(breathTimer)}
function reflection(){const q=questions[Math.floor(Math.random()*questions.length)];$('#reflection').innerHTML=`<div class="kicker">تأمل ذاتي</div><h1>سؤال اليوم</h1><div class="card"><h3>${q}</h3><textarea id="refInput" placeholder="اكتب إجابتك هنا..."></textarea><button class="btn" onclick="saveReflection('${q.replace(/'/g,'')}')">حفظ الإجابة</button></div>${notesList('reflections')}`}
function saveReflection(q){const v=$('#refInput').value.trim();if(!v)return toast('اكتب إجابة أولًا');const n=get('reflections',[]);n.unshift({date:dateAr(),title:q,text:v});set('reflections',n);toast('تم حفظ التأمل');reflection()}
function gratitude(){ $('#gratitude').innerHTML=`<div class="kicker">امتنان</div><h1>دفتر الامتنان</h1><p class="lead">اكتب شيئًا محددًا، فالكتابة المنتظمة تساعد على ملاحظة ما يعمل في يومك.</p><div class="card"><textarea id="gratInput" placeholder="اليوم أنا ممتن لـ..."></textarea><button class="btn gold" onclick="saveNote('gratitude','gratInput','تم حفظ الامتنان')">حفظ</button></div>${notesList('gratitude')}`}
function journal(){ $('#journal').innerHTML=`<div class="kicker">المفكرة</div><h1>ملاحظة اليوم</h1><div class="card"><textarea id="journalInput" placeholder="كيف كان يومك؟ ماذا تعلمت؟"></textarea><button class="btn" onclick="saveNote('journal','journalInput','تم حفظ الملاحظة')">حفظ</button></div>${notesList('journal')}`}
function saveNote(k,input,msg){const v=$('#'+input).value.trim();if(!v)return toast('اكتب شيئًا أولًا');const n=get(k,[]);n.unshift({date:dateAr(),text:v});set(k,n);toast(msg);render(stack[stack.length-1])}
function notesList(k){const n=get(k,[]);return `<div class="grid">${n.slice(0,8).map(x=>`<div class="note"><small>${x.date}</small>${x.title?'<b>'+x.title+'</b><br>':''}${x.text}</div>`).join('')}</div>`}
function wheel(){const vals=get('wheelVals',wheelAreas.map(()=>5));$('#wheel').innerHTML=`<div class="kicker">عجلة الحياة</div><h1>توازن الحياة</h1><p class="lead">قيّم المجالات واخرج بخطوة تحسين واحدة.</p><div class="card"><canvas id="wheelCanvas" width="300" height="300"></canvas>${wheelAreas.map((w,i)=>`<div class="range-row"><label><span>${w}</span><b id="wv${i}">${vals[i]}</b></label><input type="range" min="1" max="10" value="${vals[i]}" oninput="wheelChange(${i},this.value)"></div>`).join('')}<button class="btn" onclick="saveWheel()">حفظ التقييم</button></div>`;drawWheel(vals)}function wheelChange(i,v){const vals=get('wheelVals',wheelAreas.map(()=>5));vals[i]=Number(v);set('wheelVals',vals);$('#wv'+i).textContent=v;drawWheel(vals)}function saveWheel(){const vals=get('wheelVals',wheelAreas.map(()=>5));const avg=vals.reduce((a,b)=>a+b,0)/vals.length*10;set('wheel',{date:dateAr(),avg,vals});toast('تم حفظ عجلة الحياة')}function drawWheel(vals){const c=$('#wheelCanvas');if(!c)return;const ctx=c.getContext('2d'),cx=150,cy=150,max=110,n=vals.length;ctx.clearRect(0,0,300,300);ctx.strokeStyle='rgba(66,95,88,.18)';for(let r=1;r<=5;r++){ctx.beginPath();ctx.arc(cx,cy,max*r/5,0,Math.PI*2);ctx.stroke()}ctx.beginPath();vals.forEach((v,i)=>{const a=-Math.PI/2+i*Math.PI*2/n,rr=max*v/10,x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle='rgba(212,163,115,.34)';ctx.fill();ctx.strokeStyle='#425F58';ctx.lineWidth=3;ctx.stroke()}
function goals(){ $('#goals').innerHTML=`<div class="kicker">الأهداف</div><h1>مخطط هدف</h1><div class="card"><textarea id="goalName" placeholder="اكتب الهدف"></textarea><textarea id="goalWhy" placeholder="لماذا هذا الهدف مهم؟"></textarea><textarea id="goalSteps" placeholder="3 خطوات صغيرة، كل خطوة بسطر"></textarea><button class="btn" onclick="saveGoal()">حفظ الهدف</button></div>${notesList('goals')}`}
function saveGoal(){const name=$('#goalName').value.trim(),why=$('#goalWhy').value.trim(),steps=$('#goalSteps').value.trim();if(!name)return toast('اكتب الهدف أولًا');const n=get('goals',[]);n.unshift({date:dateAr(),title:name,text:why+'<br>'+steps.replace(/\n/g,'<br>')});set('goals',n);toast('تم حفظ الهدف');goals()}
function matrix(){const tasks=get('matrix',[]);const qs=[['do','مهم وعاجل'],['plan','مهم غير عاجل'],['delegate','عاجل غير مهم'],['drop','غير مهم']];$('#matrix').innerHTML=`<div class="kicker">الأولويات</div><h1>مصفوفة القرار</h1><div class="card"><input id="taskInput" type="text" placeholder="اكتب مهمة"><div class="chip-list">${qs.map(q=>`<button class="chip" onclick="addTask('${q[0]}')">${q[1]}</button>`).join('')}</div></div><div class="matrix-grid">${qs.map(q=>`<div class="quad"><h3>${q[1]}</h3>${tasks.filter(t=>t.q===q[0]).map(t=>`<div class="task ${t.done?'done':''}"><span onclick="toggleTask('${t.id}')">${t.text}</span><button onclick="delTask('${t.id}')">×</button></div>`).join('')||'<p class="lead">لا يوجد</p>'}</div>`).join('')}</div>`}
function addTask(q){const input=$('#taskInput'),v=input.value.trim();if(!v)return toast('اكتب المهمة');const tasks=get('matrix',[]);tasks.push({id:Date.now()+'',q,text:v,done:false});set('matrix',tasks);matrix()}function toggleTask(id){const t=get('matrix',[]);const task=t.find(x=>x.id===id);if(task)task.done=!task.done;set('matrix',t);matrix()}function delTask(id){set('matrix',get('matrix',[]).filter(x=>x.id!==id));matrix()}
function energy(){ $('#energy').innerHTML=`<div class="kicker">الطاقة</div><h1>تدقيق الطاقة</h1><div class="card"><textarea id="enPlus" placeholder="ما الذي يزيد طاقتك؟ كل عنصر في سطر"></textarea><textarea id="enMinus" placeholder="ما الذي يستهلك طاقتك؟ كل عنصر في سطر"></textarea><button class="btn" onclick="analyzeEnergy()">حلل الطاقة</button><div class="note" id="energyResult">اكتب العناصر ثم اضغط تحليل.</div></div>`}function analyzeEnergy(){const p=$('#enPlus').value.split('\n').filter(Boolean).length,m=$('#enMinus').value.split('\n').filter(Boolean).length;$('#energyResult').textContent=p>=m?'مصادر الطاقة جيدة. اختر واحدة وكررها اليوم.':'الاستهلاك أعلى. خفف عنصرًا واحدًا اليوم.'}
function routine(){const r=get('routine',{morning:['ماء','مراجعة هدف','أولوية اليوم'],evening:['مراجعة اليوم','امتنان','تجهيز الغد']});$('#routine').innerHTML=`<div class="kicker">الروتين</div><h1>روتين صباحي ومسائي</h1>${['morning','evening'].map(k=>`<div class="card"><h3>${k==='morning'?'صباحي':'مسائي'}</h3>${r[k].map((x,i)=>`<div class="task"><span>${x}</span><button onclick="removeRoutine('${k}',${i})">×</button></div>`).join('')}<input id="${k}Input" type="text" placeholder="أضف عنصر"><button class="btn outline" onclick="addRoutine('${k}')">إضافة</button></div>`).join('')}`}function addRoutine(k){const v=$('#'+k+'Input').value.trim();if(!v)return;const r=get('routine',{morning:[],evening:[]});r[k].push(v);set('routine',r);routine()}function removeRoutine(k,i){const r=get('routine',{morning:[],evening:[]});r[k].splice(i,1);set('routine',r);routine()}
function weekly(){ $('#weekly').innerHTML=`<div class="kicker">مراجعة أسبوعية</div><h1>ماذا تعلمت؟</h1><div class="card"><textarea id="weeklyInput" placeholder="أفضل شيء هذا الأسبوع؟ ما الذي سأحسنه الأسبوع القادم؟"></textarea><button class="btn" onclick="saveNote('weekly','weeklyInput','تم حفظ المراجعة')">حفظ المراجعة</button></div>${notesList('weekly')}`}
function achievements(){const s=stat();const badges=[['الخطوة الأولى',s.journal+s.gratitude>0,'award'],['صاحب العادة',s.habitDone>=7,'habit'],['المركّز',s.focus>=3,'focus'],['المتأمل',get('reflections',[]).length>=5,'journal'],['قلب ممتن',s.gratitude>=3,'gratitude'],['الرائي',s.wheel>0,'wheel']];$('#achievements').innerHTML=`<div class="kicker">الشارات</div><h1>إنجازاتك</h1><div class="badge-grid">${badges.map(b=>`<div class="badge ${b[1]?'':'locked'}"><span class="panel-icon">${svg(b[2])}</span><h3>${b[0]}</h3><p class="lead">${b[1]?'مفتوحة':'لم تفتح بعد'}</p></div>`).join('')}</div>`}
function showSearch(){ $('#searchOverlay').classList.add('show'); renderSearch(''); $('#searchInput').focus() }function renderSearch(q){const list=[['home','الرئيسية'],...tools.map(t=>[t[0],t[1]]),['settings','الإعدادات']].filter(x=>x[1].includes(q)||x[0].includes(q));$('#searchResults').innerHTML=list.map(x=>`<button class="search-result" onclick="$('#searchOverlay').classList.remove('show');route('${x[0]}')">${x[1]}</button>`).join('')}
function bindGo(){$$('[data-go]').forEach(b=>b.onclick=()=>route(b.dataset.go))}function updateStatsAfterAction(m){toast(m);updateAll()}document.addEventListener('DOMContentLoaded',init);
